### ISSUE TITLE
Is it possible to setup the system with 4 active modules as anchor and 1 tag?

### ISSUE THREAD

**Issue by MammadAzm** [F-Army/arduino-dwm1000#204]
## Using:
 * Arduino Uno
  
### The problem:
I have done the project with 3 anchors and 1 tag. But I need to have the system with 4 anchors and 1 tag.
Do you find it possible?

**Comment by Sonic0** [comment]
I'm sorry @MammadAzm, I'm very busy and I forgot your issue. Have you found an answer?

**Comment by MammadAzm** [comment]
@Sonic0, thank you.
Not really but I decided to progress my project with 3 active anchors. Now my issue is how to have two or more active tags simultaneously for real-time ranging each of them.
Here's my email. I would be glad if you have any solution or suggestion on this issue to inform me.
_mammad.azimi2000@gmail.com_

**Comment by Sonic0** [comment]
Hi @MammadAzm.
With our implementation of the ranging algorithm(TWR TOF), is not possible to do simultaneous ranging with a single Anchor(and not simply with two or more). To do that you need other algorithms, like TDoA, but most of them required external centralized clock synchronization for anchors (not possible with DWM1000).
With the base driver files, you have all you need to create abstraction with other algorithms.
Unfortunately, I don't remember many concepts about this topic and I'm not so useful, but there are a lot of papers online that explain all ranging and localization methods.

About 4 anchors, probably you would have liked to implement the Z axes. We studied about this topic but the time expired and this feature remained unimplemented. Now I don't remember anything about that.
