### ISSUE TITLE
Problems with BasicReceiver and BasicSender

### ISSUE THREAD

**Issue by denizlektemur** [F-Army/arduino-dwm1000#207]
Hello everyone,

Im currently working on a project where I want to determine the location of a tag using UWB.
However Im having some problems when trying to use the BasicReceiver and BasicSender examples.
The hardware Im currently using is 2x Arduino Due and 2x DWS1000.
This is the output Im getting:

![image](https://user-images.githubusercontent.com/31707186/148435070-0f728ffd-b93d-43d1-87ef-c12725cd05af.png)

It feels like the messages consist of completely random data.

I hope someone can help me with this problem.

**Comment by TCT2001** [comment]
@denizlektemur Did you fix that ?
